version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:latest
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    
    

  mysql:
    container_name: v-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
    - ./app:/app
    - ~/.m2:/root/.m2
    expose:
    - "8080"
    links:
    - mysql
    - nginx
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker

  app2:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
    - ./app:/app
    - ~/.m2:/root/.m2
    expose:
    - "8081"
    links:
    - mysql
    - nginx
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker2
